name: qr_code
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.9.2
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  get: 4.6.6
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
